name: Create Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Verify
        run: ./gradlew check
      - name: Build
        run: ./gradlew shadowJar
      - name: Publish to GitHub Packages Apache Maven
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Setup release information
        id: release_info
        run: |
          export RELEASE_VERSION=`./gradlew properties -q | grep "version:" | awk '{print $2}'`
          echo "::set-output name=release_version::${RELEASE_VERSION}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.release_info.outputs.release_version }}
          draft: false
          prerelease: false
          files: |
            commit-analytics/build/libs/flink-repository-analytics-commit-analytics-${{ steps.release_info.outputs.release_version }}.jar
            import/build/libs/flink-repository-analytics-import-${{ steps.release_info.outputs.release_version }}.jar
            sql-functions/build/libs/flink-repository-analytics-sql-functions-${{ steps.release_info.outputs.release_version }}.jar
          token: ${{ github.token }}
          fail_on_unmatched_files: true
