name: Create Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Verify
        run: ./gradlew check
      - name: Build
        run: ./gradlew shadowJar
      - name: Publish to GitHub Packages Apache Maven
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Setup release information
        id: release_info
        run: |
          export RELEASE_VERSION=`./gradlew properties -q | grep "version:" | awk '{print $2}'`
          echo "::set-output name=release_version::${RELEASE_VERSION}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.release_info.outputs.release_version }}
          body:
          draft: false
          prerelease: false
